# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField()),
                ('Place', models.PositiveIntegerField()),
                ('Faculty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Student', models.PositiveIntegerField()),
                ('ID_Hostel', models.PositiveIntegerField()),
                ('Number', models.CharField(max_length=10)),
                ('Sex', models.CharField(max_length=5)),
                ('Room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab7.HostelModel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField()),
                ('ID_Hostel', models.PositiveIntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Faculty', models.CharField(max_length=10)),
                ('Group', models.CharField(max_length=10)),
                ('Support', models.CharField(max_length=1000)),
                ('Sex', models.CharField(max_length=5)),
                ('Room', models.CharField(max_length=10)),
            ],
        ),
    ]
